### ISSUE TITLE
HiFiGAN vocoder support in TTS

### ISSUE THREAD

**Issue by ahazned** [espnet/espnet_onnx#48]
Hi,

Supported vocoders include HiFiGAN in https://github.com/espnet/espnet_onnx/blob/master/docs/TTSSupported.md, but in the code HiFiGAN seems to be not supported in the vocoder loader function below. 

Any idea how to use the HiFiGAN vocoder? I am also attaching the config.yaml file that TTSModelExport  created -> [config.yaml](https://github.com/espnet/espnet_onnx/files/9606489/config.yaml.txt)

https://github.com/espnet/espnet_onnx/blob/eb93c762d20c9b9c6c5d72ab1a0d56f07fa40b88/espnet_onnx/tts/abs_tts_model.py#L59-L70

**Comment by Masao-Someki** [comment]
Hi @ahazned,
HiFiGAN is included in vocoder_type == 'OnnxVocoder'.
ParallelWaveGAN, MelGAN, and HiFiGAN can be converted into one onnx model, and we load it from [here](https://github.com/espnet/espnet_onnx/blob/eb93c762d20c9b9c6c5d72ab1a0d56f07fa40b88/espnet_onnx/tts/model/vocoders/vocoder.py)
Since we do not need to separate the inference class, the loader function  do not separate HiFiGAN.
